vich_uploader:
  db_driver: orm

  mappings:
    buddy_images:
      uri_prefix: /uploads/images
      upload_destination: '%kernel.project_dir%/public/uploads/images'
      namer: Vich\UploaderBundle\Naming\UniqidNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true